services:
  web:
    build: ..
    environment:
      - TEST_TIME_IMAGES_PATH=/test_time_images/
      - PROD=1
      - DEBUG=true
      - LOG_FILE=/fastapi/app.log
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi
      - MODEL_TYPE=random
    ports: 
     - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
    ports:
      - 5432:5432

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ../grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../grafana_data
  postgres_data:

networks:
  default: 
    name: hello_fastapi